# SMPL directories
SMPL_MODELS_PATH: "model"
SMPL_ASSETS_PATH: "assets"

# Keypoints directories for kinect
KEYPOINTS_2D_ROOT: "/home/data/hot_kinect_2d_joints/"
KEYPOINTS_3D_ROOT: "/home/data/hot_kinect_3d_joints/"
